###
GET http://localhost:8080/user/ten%0A2022-12-18%2017%3A55%3A00.038%20%5BeventLoopGroupProxy-3-2%5D%20INFO%20I%20am%20a%20forged%20log%20entry
Accept: application/json

### %0D = \r = carriage return
GET http://localhost:8080/user/ten%0D2022-12-21%2016%3A37%3A20.600%20%5BeventLoopGroupProxy-4-4%5D%20TRACE%20i.k.s.p.c.ContentNegotiation%20-%20Skipping%20because%20body%20is%20already%20converted.%20I%20am%20forged.
Accept: application/json

### %0A = \n = new line
GET http://localhost:8080/user/test%0A2022-12-21%2016%3A37%3A20.600%20%5BeventLoopGroupProxy-4-4%5D%20TRACE%20i.k.s.p.c.ContentNegotiation%20-%20Skipping%20because%20body%20is%20already%20converted.%20I%20am%20forged.
Accept: application/json


### %0D = \r = carriage return
GET http://localhost:8080/user/notsanitized/ten%0D2022-12-21%2016%3A37%3A20.600%20%5BeventLoopGroupProxy-4-4%5D%20TRACE%20i.k.s.p.c.ContentNegotiation%20-%20Skipping%20because%20body%20is%20already%20converted.%20I%20am%20forged.
Accept: application/json

### %0A = \n = new line
GET http://localhost:8080/user/notsanitized/test%0A2022-12-21%2016%3A37%3A20.600%20%5BeventLoopGroupProxy-4-4%5D%20TRACE%20i.k.s.p.c.ContentNegotiation%20-%20Skipping%20because%20body%20is%20already%20converted.%20I%20am%20forged.
Accept: application/json





### Basic auth
GET http://localhost:8080/user
Authorization: Basic Harry 1234
Accept: application/json

### Basic auth
GET http://localhost:8080/user
Authorization: Basic Not_Harry 1234
Accept: application/json

### Basic auth (fails)
GET http://localhost:8080/user
Authorization: Basic Harry 12345
Accept: application/json


###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": "0",
  "userName": "Jack",
  "password": "1234",
  "email": "jack@mail.com"
}

###
GET http://localhost:8080/user/0
Accept: application/json
