[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.10.1",
    "tiktoken>=0.9.0",
    "openai (>=1.93.0,<2.0.0)",
    "streamlit>=1.46.1",
]
